### ISSUE TITLE
Bug: Doesn't work with beta versions of electron

### ISSUE THREAD

**Issue by amilajack** [lgeiger/node-abi#38]
```
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 2.0.0-beta.1 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 2.0.0-beta.1 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/project/node_modules/node-abi/index.js:30:9)
    at new Rebuilder (/project/node_modules/electron-rebuild/lib/src/rebuild.js:64:28)
    at rebuildWithOptions (/project/node_modules/electron-rebuild/lib/src/rebuild.js:310:23)
    at Object.doRebuild [as rebuild] (/project/node_modules/electron-rebuild/lib/src/rebuild.js:317:16)
    at Object.<anonymous> (/project/node_modules/electron-rebuild/lib/src/cli.js:114:33)
    at Generator.next (<anonymous>)
    at /project/node_modules/electron-rebuild/lib/src/cli.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/project/node_modules/electron-rebuild/lib/src/cli.js:4:12)
    at /project/node_modules/electron-rebuild/lib/src/cli.js:69:8
child_process.js:614
    throw err;
```

What's the way to fix this?

**Comment by MarshallOfSound** [comment]
> Updating "node-abi" might help solve this issue if it is a new release of electron

**Comment by amilajack** [comment]
Just checked [the source in master](https://github.com/lgeiger/node-abi/blob/master/index.js#L65) and it seems like electron `1.8.0` is the latest supported version

**Comment by MarshallOfSound** [comment]
@amilajack See https://github.com/lgeiger/node-abi/blob/master/index.js#L94 `2.0.0-beta.1` definitely works 👍

**Comment by lgeiger** [comment]
Just checked, that this is working correctly in the latest version: https://runkit.com/embed/fcf04gpmoamc
